### ISSUE TITLE
Add template parameter for automatic casting in event argument value function.

### ISSUE THREAD

**Issue by lohne150** [Per-Morten/imt3912_dev#116]
Wants this function as getting arguments at this point is not as easy as it could be. I would prefer that you have a template parameter in the value function which you can enter a type that the function casts the const void* value for you. In addition it's default argument could just be const void* so no previous usage of the function needs to be changed.

**Comment by Per-Morten** [comment]
Will look into it, don't really think it should be a problem, it might lead to some redundant compiler work, but it should not be noticeable for just a cast.
