### ISSUE TITLE
Error related to nox world manager and the ecs entity manager

### ISSUE THREAD

**Issue by lohne150** [Per-Morten/imt3912_dev#124]
A bug where the world manager of nox starts having errors in the ecs console template when including the ecs entityManager anywhere before you include the nox world manager. No idea why this is happening, the text below is the error that it outputs. 

// Just regular cmake output above this point
[ 99%] Built target nox_numerous_unique_components
In file included from /home/trond/School/Bachelor/imt3912_dev/tests/ecs/console_template/src/console_application.cpp:15:0:
/home/trond/School/Bachelor/imt3912_dev/nox-engine/include/nox/logic/world/Manager.h:258:10: error: ‘ThreadSafeQueue’ in namespace ‘nox::thread’ does not name a template type
  thread::ThreadSafeQueue<actor::Identifier> actorRemovalQueue;
          ^
/home/trond/School/Bachelor/imt3912_dev/nox-engine/include/nox/logic/world/Manager.h:259:10: error: ‘ThreadSafeQueue’ in namespace ‘nox::thread’ does not name a template type
  thread::ThreadSafeQueue<std::unique_ptr<actor::Actor>> actorManagementQueue;
          ^
tests/ecs/console_template/CMakeFiles/ecs_console_template.dir/build.make:86: recipe for target 'tests/ecs/console_template/CMakeFiles/ecs_console_template.dir/src/console_application.cpp.o' failed
make[2]: *** [tests/ecs/console_template/CMakeFiles/ecs_console_template.dir/src/console_application.cpp.o] Error 1
CMakeFiles/Makefile2:2096: recipe for target 'tests/ecs/console_template/CMakeFiles/ecs_console_template.dir/all' failed
make[1]: *** [tests/ecs/console_template/CMakeFiles/ecs_console_template.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

I have pushed up the code causing this error in this issues corresponding issue number. It is the project located in repo_root/tests/ecs/console_template.

**Comment by Per-Morten** [comment]
Cant reproduce, getting this error when trying to run cmake.
CMake Error at CMakeLists.txt:161 (add_subdirectory):
  add_subdirectory given source "cmd" which is not an existing directory.


-- Configuring incomplete, errors occurred!
See also "/home/per-morten/School/ntnu/6th_semester/imt3912_thesis/imt3912_dev/build/CMakeFiles/CMakeOutput.log".
See also "/home/per-morten/School/ntnu/6th_semester/imt3912_thesis/imt3912_dev/build/CMakeFiles/CMakeError.log".
